name: Generate Conventional Changelog

on:
  push:
    tags:
      - "v*.*.*" # Run on version tag push

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository with full history
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full commit history is fetched, including tags

      # Step 2: Find the branch associated with the commit
      - name: Determine the branch
        id: extract_branch
        run: |
          # Try to find the branch based on commit history
          BRANCH=$(git for-each-ref --format='%(refname:short)' $(git rev-parse --verify HEAD) | grep 'heads/' | head -n 1 | sed 's|heads/||')
          echo "Branch: $BRANCH"
          if [ -z "$BRANCH" ]; then
            echo "No branch found, defaulting to 'main'"
            BRANCH="main"  # Fallback to 'main' if no branch is found
          fi
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      # Step 3: Set up Node.js environment to install conventional-changelog
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 4: Install conventional-changelog-cli
      - name: Install conventional-changelog-cli
        run: |
          npm install -g conventional-changelog-cli

      # Step 5: Generate changelog
      - name: Generate changelog
        run: |
          conventional-changelog -p angular -i CHANGELOG.md -s -r 0

      # Step 6: Commit and push the changelog to the determined branch
      - name: Commit and push changelog
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: update changelog for ${GITHUB_REF#refs/tags/}"

          # Push to the determined branch
          git push origin HEAD:${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
